version: '3'

networks:
  cup:

services:
  peer0.cipbancos.org.br:
    container_name: peer0.cipbancos.org.br
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.cipbancos.org.br
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=CIPMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.cipbancos.org.br:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=cup_cup
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    volumes:
      - /var/run/:/host/var/run/
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/peers/peer0.cipbancos.org.br/msp:/etc/hyperledger/msp/peer
      - ./config/crypto-config/peerOrganizations/cipbancos.org.br/users:/etc/hyperledger/msp/users
      - ./config/config:/etc/hyperledger/configtx
      - ./chaincode/:/opt/gopath/src/github.com/
    networks:
      - cup
  
  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - cup
  
  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.cipbancos.org.br:7051
      - CORE_PEER_LOCALMSPID=CIPMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cipbancos.org.br/users/Admin@cipbancos.org.br/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/
      - ./config/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - cup
    #depends_on:
    #  - orderer.cipbancos.org.br
    #  - peer0.cipbancos.org.br
    #  - couchdb
  
  webapp:
    container_name: webapp
    build:
      dockerfile: ./tomcat.dockerfile
      context: .
    image: fmesquita92/tomcat
    ports:
      - "8081:8080"
    extra_hosts:
      - "orderer.cipbancos.org.br:10.150.162.190"
      - "ca.cipbancos.org.br:10.150.162.190"
    volumes:
      - ./webapp-volume/webapps:/usr/local/tomcat/webapps
      - ./webapp-volume/minerva:/usr/local/minerva/
      - ./webapp-volume/h2db:/root
    networks:
      - cup